services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass 'qwe123!@#' --appendonly yes
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: zhiguang
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis-data:
  mysql-data:
